language: elixir
elixir:
- 1.7.4
otp_release:
- 21.2.2
before_install:
- ./scripts/travis/before-install.sh
before_script:
- ./scripts/travis/before-script.sh
services:
- postgresql

cache:
  directories:
  - _build
  - deps

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-10-postgis-2.4
    - postgresql-10-postgis-2.4-scripts
    - postgresql-client-10
  s3_region: "eu-west-1"
  artifacts:
    region: "eu-west-1"
    paths:
    - ./app.tar.gz
    target_paths:
    - unfold-server/$TRAVIS_BRANCH/latest
    - unfold-server/$TRAVIS_BRANCH/builds/$TRAVIS_BUILD_NUMBER

script:
- ./scripts/travis/deploy.sh

# after_success:
# - ./scripts/travis/deploy.sh
after_success:
  - ./scripts/travis/discord-hook.sh success $WEBHOOK_URL
after_failure:
  
  - ./scripts/travis/discord-hook.sh failure $WEBHOOK_URL

env:
  global:
  - MIX_ENV=test
  - PGPORT=5433